### ISSUE TITLE
Fix deprecation from Symfony 6.3

### ISSUE THREAD

**Issue by HEKET313** [jeromegamez/ramsey-uuid-normalizer#3]
Since symfony/serializer 6.3: \"Gamez\\Symfony\\Component\\Serializer\\Normalizer\\UuidNormalizer\" should implement \"DenormalizerInterface::getSupportedTypes(?string $format): array\".

**Comment by jeromegamez** [comment]
Sorry for the late reply! Please update to https://github.com/jeromegamez/ramsey-uuid-normalizer/releases/tag/3.1.0 , this should fix the problem (it requires at least Symfony 6.4, though).
